keyMirror = require 'react/lib/keyMirror'

module.exports = keyMirror({
    SAVE: null,
    SAVE_SUCCESS: null,
    SAVE_FAIL: null,
    RECEIVED_ALL_CONTACTS: null,
    GET_ALL_CONTACTS_FAIL:null,
    GET_CONTACTS:null,
    CONTACT_DELETED: null,
    DELETED_CONTACTS: null,
    DELETE_CONTACTS_FAIL: null,
    SAVE_MULTIPLE_CONTACTS_SUCCESS:null,
    GET_VARIABLES_SUCCESS:null,
    GET_VARIABLES_FAIL:null,
    CREATE_VARIABLE_SUCCESS:null,
    CREATE_VARIABLE_FAIL:null,
    SELECT_CONTACT:null,
    TRIGGER_CHANGE:null,
    CLEAN:null,
    SEARCH_CONTACTS:null,
    GET_SEARCHED_CONTACTS_FAIL:null,
    RECEIVED_SEARCHED_CONTACTS:null,
    EDIT_CONTACT:null,
    AGGREGATE_GROUPS:null,
    UPDATED_CONTACTS:null,
    CLEAR_EDITED_CONTACT:null,
    UPDATE_CONTACT:null,
    SELECT_ALL_CONTACTS:null
});
