node:
    image: zulfat/smsgateway
    links:
        - redis:redis
        - mongodb:mongodb
    ports:
        - "3200:3200"
mongodb:
    image: mongodb
    command: mongod --smallfiles
    ports:
        - "27017:27017"
    volumes:
        - /data/db
redis:
    image: redis
    ports:
        - "6379"